# Generated by Django 4.1.2 on 2022-11-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackme', '0002_remove_journalentry_dv_k_remove_journalentry_dv_phos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user_name',
        ),
    ]
