# Generated by Django 4.1.2 on 2022-11-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackme', '0003_remove_person_password_remove_person_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_name',
            field=models.CharField(default='name', max_length=20),
        ),
    ]
