# Generated by Django 4.1.2 on 2022-11-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackme', '0004_person_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='DV_k',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='DV_phos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='DV_protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='DV_sodium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='DV_water',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
